### ISSUE TITLE
ChromeOS PPD under 250KiB

### ISSUE THREAD

**Issue by blackICE19240** [matthiasbock/Canon-PIXMA-iP7250-driver#2]
Is there any chance you could make these compatible with Chrome OS?

**Comment by matthiasbock** [comment]
Please be more specific. What exactly did you try, what did you expect and what happened instead?

**Comment by blackICE19240** [comment]
Thanks for replying. 
In Chrome OS, to add a local printer it seems you have to use a PPD file to add a driver but annoyingly it has to be less than 250KB and yours is about 260KB. I tried removing the translations to make it smaller but when I try to add the printer I get, "File is the wrong format. Check PPD file and try again". This is probably because I didn't know what I was doing but it could be that chrome OS uses a different format all together. I hoped you could help?

**Comment by matthiasbock** [comment]
It seems to me the real issue here is the size limitation for PPD files in Chrome OS then.
As for your error, I presume you broke the PPD file when you edited it.
Please attach your edited PPD file to your next comment.
Note, that installing the PPD alone will not suffice to get your printer to work.
You will need to build and install also the rest of the repository.

**Comment by blackICE19240** [comment]
It makes sense that those files are too small to contain the information necessary but how then would it be possible that this is all Chrome OS requires?
[canonip7200 - new.ppd.zip](https://github.com/matthiasbock/Canon-PIXMA-iP7250-driver/files/3056301/canonip7200.-.new.ppd.zip)

**Comment by matthiasbock** [comment]
As I wrote before, the PPD alone is not sufficient. At first glance I see no problem with your PPD. Please try cloning, building and installing the complete repository. You can use the Makefile in the root folder. Simply type:
~~~
$ make && make install
~~~

Then in the ppd/ folder type:
~~~
$ ./autogen.sh && make && make install
~~~

You might have to be sudoer (or root) in order to install the binaries.

**Comment by blackICE19240** [comment]
I would but this is Chrome OS not linux, I don't see how this would be possible.

**Comment by matthiasbock** [comment]
Chrome OS is a distribution of Linux. The commands I wrote in my previous comment are to be entered within the cloned repository on a console or terminal emulator such as xterm. Unfortunately, I can't tell you how to open one on Chrome OS. I'm afraid you have to figure that part out by yourself.

**Comment by blackICE19240** [comment]
Ohhh right. I'll give it a go this weekend/tomorrow then. 
Thanks a lot for helping me by the way.

**Comment by blackICE19240** [comment]
I've managed to get a working terminal (crosh shell) by enabling developer mode but I don't think it's possible to install Make. Have you got any suggestions?

**Comment by matthiasbock** [comment]
Sorry, no. I'm not familiar with ChromeOS.

**Comment by blackICE19240** [comment]
Oh well. Thanks for everything anyway ... and sorry for the slow reply.

**Comment by dimpase** [comment]
It seems there are more problems with ppd files on ChromeOS than just the size. I have the same error with a perfectly OK ppd file, which is just 50K in size.
